### ISSUE TITLE
SPS30 always returning equal PM2.5 and PM10 concentrations 

### ISSUE THREAD

**Issue by ishan2109** [Sensirion/arduino-sps#31] opened 2021-02-08 05:40 UTC
The PM2.5 and PM10 mass concentration values returned by SPS30 are always in a very close range(difference <=1 ug/m3, screenshot attached below).I have used the code directly.

I am using NodeMCUv1.0 and an external power supply 5V 2A just to make sure there is no issue with power.
I also have  SDS011 sensor by Nova Fitness and Aeroqual. Both of them have are returning PM2.5 and PM10 values with a significant difference (at least 5-10 ug/m3). 

I am not sure if there is a problem with sensor or I need to do some modifications in the code itself?

![Screenshot (14)](https://user-images.githubusercontent.com/31300846/107180092-00258280-69fe-11eb-9c6e-b12cd6e43b8f.png)

**Comment by rnestler** [comment] 2021-02-08 14:18
Hi @ishan2109
I don't see anything wrong that would point in the direction of any issue with the code itself.
Since we can't really give support here regarding the sensors performance, I recommend you to contact support via https://www.sensirion.com/en/about-us/contact/

**Comment by winkj** [comment] 2021-02-08 17:18
Duplicate of #27

**Closed by winkj** 2021-02-08 17:18 UTC
Labels: duplicate
